export const data = {
  featured: [
    {
      id: 1,
      img: "https://lyricalcorp.com/assets/images/handcraftedheaven/bracelets.png",
      title: "Lorem Ipsum",
      isNew: true,
      oldPrice: 500,
      newPrice: 450,
    },
    {
      id: 2,
      img: "https://lyricalcorp.com/assets/images/handcraftedheaven/bracelets.png",
      title: "Lorem Ipsum",
      isNew: true,
      oldPrice: 160,
      newPrice: 80,
    },
    {
      id: 3,
      img: "https://lyricalcorp.com/assets/images/handcraftedheaven/bracelets.png",
      title: "Lorem Ipsum",
      oldPrice: 300,
      newPrice: 200,
    },
    {
      id: 4,
      img: "https://lyricalcorp.com/assets/images/handcraftedheaven/bracelets.png",
      title: "Lorem Ipsum",
      oldPrice: 300,
      newPrice: 280,
    },
  ],
  trending: [
    {
      id: 1,
      img: "https://lyricalcorp.com/assets/images/handcraftedheaven/bracelets.png",
      title: "Lorem Ipsum",
      oldPrice: 100,
      newPrice: 80,
    },
    {
      id: 2,
      img: "https://lyricalcorp.com/assets/images/handcraftedheaven/bracelets.png",
      title: "Lorem Ipsum",
      isNew: true,
      oldPrice: 750,
      newPrice: 500,
    },
    {
      id: 3,
      img: "https://lyricalcorp.com/assets/images/handcraftedheaven/bracelets.png",
      title: "Lorem Ipsum",
      oldPrice: 300,
      newPrice: 280,
    },
    {
      id: 4,
      img: "https://lyricalcorp.com/assets/images/handcraftedheaven/bracelets.png",
      title: "Lorem Ipsum",
      isNew: true,
      oldPrice: 150,
      newPrice: 125,
    },
  ],
};
