export const data = {
  acc: [
    {
      id: 1,
      img: "https://lyricalcorp.com/assets/images/handcraftedheaven/beads.png",
      title: "Beads",
      isNew: true,
      oldPrice: 30,
      newPrice: 20,
    },
    {
      id: 2,
      img: "https://lyricalcorp.com/assets/images/handcraftedheaven/headwear.png",
      title: "Headwear",
      oldPrice: 50,
      newPrice: 30,
    },
    {
      id: 3,
      img: "https://lyricalcorp.com/assets/images/handcraftedheaven/hairchain.png",
      title: "Hair Chain",
      oldPrice: 30,
      newPrice: 10,
    },
  ],
  embroidery: [
    {
      id: 1,
      img: "https://lyricalcorp.com/assets/images/handcraftedheaven/embroidery1.png",
      title: "Embroidery",
      isNew: true,
      oldPrice: 100,
      newPrice: 50,
    },
    {
      id: 2,
      img: "https://lyricalcorp.com/assets/images/handcraftedheaven/embroidery2.png",
      title: "Carpet Embroidery",
      oldPrice: "500",
      newPrice: "400",
    },
    {
      id: 3,
      img: "https://lyricalcorp.com/assets/images/handcraftedheaven/embroidery3.png",
      title: "Hat Embroidery",
      oldPrice: "250",
      newPrice: "150",
    },
  ],
  handCrafts: [
    {
      id: 1,
      img: "https://lyricalcorp.com/assets/images/handcraftedheaven/Statue.png",
      title: "Statue",
      isNew: true,
      oldPrice: 350,
      newPrice: 280,
    },
    {
      id: 2,
      img: "https://lyricalcorp.com/assets/images/handcraftedheaven/handbag.png",
      title: "Hand Bag",
      oldPrice: 300,
      newPrice: 125,
    },
    {
      id: 3,
      img: "https://lyricalcorp.com/assets/images/handcraftedheaven/basket.png",
      title: "Basket",
      oldPrice: 300,
      newPrice: 280,
    },
    {
      id: 4,
      img: "https://lyricalcorp.com/assets/images/handcraftedheaven/painting.png",
      title: "Painting",
      oldPrice: 400,
      newPrice: 175,
    },
    {
      id: 5,
      img: "https://lyricalcorp.com/assets/images/handcraftedheaven/painting1.png",
      title: "Colorful Painting",
      oldPrice: 450,
      newPrice: 300,
    },
    {
      id: 6,
      img: "https://lyricalcorp.com/assets/images/handcraftedheaven/bathroommirror.png",
      title: "Bathroom Mirror",
      oldPrice: 550,
      newPrice: 350,
    },
  ],
  paperCrafts: [
    {
      id: 1,
      img: "https://lyricalcorp.com/assets/images/handcraftedheaven/papercrafts.png",
      title: "Paper Flamingos",
      isNew: true,
      oldPrice: 20,
      newPrice: 5,
    },
    {
      id: 2,
      img: "https://lyricalcorp.com/assets/images/handcraftedheaven/windmill.png",
      title: "Paper Windmill",
      isNew: true,
      oldPrice: 10,
      newPrice: 2,
    },
    {
      id: 3,
      img: "https://lyricalcorp.com/assets/images/handcraftedheaven/papertoy.png",
      title: "Paper Boy",
      isNew: true,
      oldPrice: 10,
      newPrice: 2,
    },
  ],
  jewelry: [
    {
      id: 1,
      img: "https://lyricalcorp.com/assets/images/handcraftedheaven/Diamond%20Ring.png",
      title: "Diamond Ring",
      isNew: true,
      oldPrice: 2580,
      newPrice: 2080,
    },
    {
      id: 2,
      img: "https://lyricalcorp.com/assets/images/handcraftedheaven/Rings.png",
      title: "Copper Rings",
      isNew: true,
      oldPrice: 300,
      newPrice: 240,
    },
    {
      id: 3,
      img: "https://lyricalcorp.com/assets/images/handcraftedheaven/Pink%20Quartz%20Necklace%20-%20Rosy%20Glow.png",
      title: "Pink Quartz Necklace - Rosy Glow",
      oldPrice: 1000,
      newPrice: 1000,
    },
  ],
  woodworking: [
    {
      id: 1,
      img: "https://lyricalcorp.com/assets/images/handcraftedheaven/bracelets.png",
      title: "Lorem Ipsum",
      isNew: true,
      oldPrice: 120,
      newPrice: 80,
    },
    {
      id: 2,
      img: "https://lyricalcorp.com/assets/images/handcraftedheaven/bracelets.png",
      title: "Lorem Ipsum",
      oldPrice: 550,
      newPrice: 300,
    },
    {
      id: 3,
      img: "https://lyricalcorp.com/assets/images/handcraftedheaven/bracelets.png",
      title: "Lorem Ipsum",
      oldPrice: 250,
      newPrice: 220,
    },
    {
      id: 4,
      img: "https://lyricalcorp.com/assets/images/handcraftedheaven/bracelets.png",
      title: "Lorem Ipsum",
      oldPrice: 100,
      newPrice: 80,
    },
  ],
};
