export const data = {
  acc: [
    {
      id: 1,
      img: "https://lyricalcorp.com/assets/images/handcraftedheaven/bracelets.png",
      title: "Lorem Ipsum",
      isNew: true,
      oldPrice: 1100,
      newPrice: 800,
    },
    {
      id: 2,
      img: "https://lyricalcorp.com/assets/images/handcraftedheaven/bracelets.png",
      title: "Lorem Ipsum",
      oldPrice: 500,
      newPrice: 480,
    },
    {
      id: 3,
      img: "https://lyricalcorp.com/assets/images/handcraftedheaven/bracelets.png",
      title: "Lorem Ipsum",
      oldPrice: 300,
      newPrice: 280,
    },
    {
      id: 4,
      img: "https://lyricalcorp.com/assets/images/handcraftedheaven/bracelets.png",
      title: "Lorem Ipsum",
      oldPrice: 120,
      newPrice: 100,
    },
  ],
  embroidery: [
    {
      id: 1,
      img: "https://lyricalcorp.com/assets/images/handcraftedheaven/bracelets.png",
      title: "Lorem Ipsum",
      isNew: true,
      oldPrice: 1500,
      newPrice: 1350,
    },
    {
      id: 2,
      img: "https://lyricalcorp.com/assets/images/handcraftedheaven/bracelets.png",
      title: "Lorem Ipsum",
      oldPrice: "500 per m",
      newPrice: "400 per m",
    },
    {
      id: 3,
      img: "https://lyricalcorp.com/assets/images/handcraftedheaven/bracelets.png",
      title: "Lorem Ipsum",
      oldPrice: "500 per m",
      newPrice: "450 per m",
    },
    {
      id: 4,
      img: "https://lyricalcorp.com/assets/images/handcraftedheaven/bracelets.png",
      title: "Lorem Ipsum",
      oldPrice: 2500,
      newPrice: 2400,
    },
  ],
  handCrafts: [
    {
      id: 1,
      img: "https://lyricalcorp.com/assets/images/handcraftedheaven/bracelets.png",
      title: "Lorem Ipsum",
      isNew: true,
      oldPrice: 1100,
      newPrice: 800,
    },
    {
      id: 2,
      img: "https://lyricalcorp.com/assets/images/handcraftedheaven/bracelets.png",
      title: "Lorem Ipsum",
      oldPrice: 300,
      newPrice: 200,
    },
    {
      id: 3,
      img: "https://lyricalcorp.com/assets/images/handcraftedheaven/bracelets.png",
      title: "Lorem Ipsum",
      oldPrice: 300,
      newPrice: 280,
    },
    {
      id: 4,
      img: "https://lyricalcorp.com/assets/images/handcraftedheaven/bracelets.png",
      title: "Lorem Ipsum",
      oldPrice: 400,
      newPrice: 350,
    },
    {
      id: 5,
      img: "https://lyricalcorp.com/assets/images/handcraftedheaven/bracelets.png",
      title: "Lorem Ipsum",
      oldPrice: 450,
      newPrice: 300,
    },
  ],
  paperCrafts: [
    {
      id: 1,
      img: "https://lyricalcorp.com/assets/images/handcraftedheaven/bracelets.png",
      title: "Lorem Ipsum",
      isNew: true,
      oldPrice: 1100,
      newPrice: 800,
    },
    {
      id: 2,
      img: "https://lyricalcorp.com/assets/images/handcraftedheaven/bracelets.png",
      title: "Lorem Ipsum",
      isNew: true,
      oldPrice: 250,
      newPrice: 200,
    },
    {
      id: 3,
      img: "https://lyricalcorp.com/assets/images/handcraftedheaven/bracelets.png",
      title: "Lorem Ipsum",
      oldPrice: 280,
      newPrice: 250,
    },
    {
      id: 4,
      img: "https://lyricalcorp.com/assets/images/handcraftedheaven/bracelets.png",
      title: "Lorem Ipsum",
      oldPrice: 300,
      newPrice: 280,
    },
    {
      id: 5,
      img: "https://lyricalcorp.com/assets/images/handcraftedheaven/bracelets.png",
      title: "Lorem Ipsum",
      oldPrice: 560,
      newPrice: 500,
    },
  ],
  jewelry: [
    {
      id: 1,
      img: "https://lyricalcorp.com/assets/images/handcraftedheaven/bracelets.png",
      title: "Lorem Ipsum",
      isNew: true,
      oldPrice: 1500,
      newPrice: 1400,
    },
    {
      id: 2,
      img: "https://lyricalcorp.com/assets/images/handcraftedheaven/bracelets.png",
      title: "Lorem Ipsum",
      isNew: true,
      oldPrice: 300,
      newPrice: 240,
    },
    {
      id: 3,
      img: "https://lyricalcorp.com/assets/images/handcraftedheaven/bracelets.png",
      title: "Lorem Ipsum",
      oldPrice: 600,
      newPrice: 580,
    },
    {
      id: 4,
      img: "https://lyricalcorp.com/assets/images/handcraftedheaven/bracelets.png",
      title: "Lorem Ipsum",
      oldPrice: 300,
      newPrice: 280,
    },
  ],
  woodworking: [
    {
      id: 1,
      img: "https://lyricalcorp.com/assets/images/handcraftedheaven/bracelets.png",
      title: "Lorem Ipsum",
      isNew: true,
      oldPrice: 120,
      newPrice: 80,
    },
    {
      id: 2,
      img: "https://lyricalcorp.com/assets/images/handcraftedheaven/bracelets.png",
      title: "Lorem Ipsum",
      oldPrice: 550,
      newPrice: 300,
    },
    {
      id: 3,
      img: "https://lyricalcorp.com/assets/images/handcraftedheaven/bracelets.png",
      title: "Lorem Ipsum",
      oldPrice: 250,
      newPrice: 220,
    },
    {
      id: 4,
      img: "https://lyricalcorp.com/assets/images/handcraftedheaven/bracelets.png",
      title: "Lorem Ipsum",
      oldPrice: 100,
      newPrice: 80,
    },
  ],
};
